name: Build and Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build image
        run: docker build ./api/ -t braedonharder/node-app:latest
      - name: push image to docker hub
        run: 
          docker login-u braedonharder -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push braedonharder/node-app:1.0